### ISSUE TITLE
FieldResolverError with Subscriptions

### ISSUE THREAD

**Issue by Thinkenterprise** [graphql-java/graphql-java-tools#184] opened 2018-09-28 14:51 UTC
Hi, 
I try to start the subscription example graphql-spring-boot/example-graphql-subscription with the versions.

spring boot 2.0.3
graphql spring boot 5.0.2
graphiql spring boot 5.0.2
tools 5.2.4
rxjava 2.1.5

Without Subscriptions the example runs fine. But with Subscription I got the following error message during the startup of the application.

om.coxautodev.graphql.tools.FieldResolverError: No method found with any of the following signatures (with or without one of [interface graphql.schema.DataFetchingEnvironment] as the last argument), in priority order:
com.oembedler.moon.graphql.boot.resolvers.StockSubscription.stockQuotes(~stockCodes)
com.oembedler.moon.graphql.boot.resolvers.StockSubscription.getStockQuotes(~stockCodes)

**It seems to be a problem in graphql tools**. Graphql tools does not seem to expect a return value.
But the Return type should be a Publisher right?

Best Regards
Michael

**Comment by oliemansm** [comment] 2018-09-28 15:47
This is caused by #182. Try making the method `public`, that should fix it for now. Bug will be fixed in next release.

**Closed** 2018-09-28 15:48 UTC
Labels: bug

**Comment by Thinkenterprise** [comment] 2018-09-28 18:12
... thanks for your fast response. It works now:-)
