### ISSUE TITLE
Inherited GraphQLResolvers do not find Data class type

### ISSUE THREAD

**Issue by jndonald3** [graphql-java/graphql-java-tools#145] opened 2018-06-13 03:29 UTC
If you have a resolver which inherits from a base resolver passing in the type parameter T, then the schema parser is unable to resolve the data class correctly. Something like:

```kotlin
class BaseResolver<T>: GraphQLResolver<T> {
//TODO: useful code here
}

class UserResolver: BaseResolver<User> {
//TODO: other stuff
}
```
When building the schema, the parser throws:
```kotlin
"Unable to determine data class for resolver '${resolverType.name}' from generic interface!  This is most likely a bug with graphql-java-tools."
```

As a side note, I tried to get around this issue with interfaces and the same error popped up:
```kotlin
interface IBaseResolver<T>: GraphQLResolver<T> {
//TODO: useful code here
}

class UserResolver: IBaseResolver<User> {
//TODO: other stuff
}
```

*My use case is that i wanted to do constructor injection of application config,db instance, etc... for all my resolvers (which requires some base class or interface). I've found a way around it by not directly inheriting from `GraphQLResolver`, but it's not ideal.

**Comment by alexgenco** [comment] 2018-07-19 18:38
I'm having a similar problem. Given the following schema:

```graphql
interface Named {
  name: String
}
```

and a Resolver

```java
public class NameResolver<T extends Named> implements GraphQLResolver<T> {
  public String doThing(T named) {
    // ...
  }
}
```

I get the following exception:

```
com.coxautodev.graphql.tools.ResolverError: Unable to determine data class for resolver 'app.schema.resolvers.NameResolver' from generic interface!  This is most likely a bug with graphql-java-tools.
```

Are generic resolvers not supported?

**Comment by alexgenco** [comment] 2018-07-19 20:23
Also if I change the resolver to

```java
public class NameResolver implements GraphQLResolver<Named> {
  public String doThing(Named named) {
    // ...
  }
}
```

The following query doesn't trigger the datafetcher (assuming `NamedImplementer` implements the `Named` interface):

```graphql
query {
  foo {
    ... on NamedImplementer {
      doThing
    }
  }
}
```

It seems like the resolvers only trigger for concrete data classes, and not any interfaces they may implement. Is there a workaround for this?

**Comment by jndonald3** [comment] 2018-07-20 19:54
@alexgenco 

Hey

I did find a way around this. Basically, when looking for the concrete class for the generic, the underlying library looks directly for a `GraphQLResolver<*>` implementation on the class. `*` here cannot be `T`, it needs to be the resolved type. Which means you can't actually do inheritance through the type.

In order to get around this, I simply implemented the interface and my subclass seperately:

```kotlin
interface IBaseResolver {
    fun inject(db: MongoDataStore, config:JsonObject)
}

class UserResolver: GraphQLResolver<User>, IBaseResolver {
    private var db:MongoDataStore? = null
    private var config:JsonObject? = null

    override fun inject(db: MongoDataStore, config: JsonObject) {
        this.db = db
        this.config = config
    }
}
```

This allows the library to find `GraphQLResolver<User>` separately from my inheritance tree and resolve the type `User` correctly.

**Comment by apottere** [comment] 2018-07-24 19:16
Right now it does only work with concrete data classes, but it should be updated to work with interfaces on parent classes and `extends` in the type argument.  I'll keep this in mind.

**Comment by oliemansm** [comment] 2018-09-22 16:14
I pushed an update for #163 that seems a duplicate of this one. It doesn't recognize `extends` (yet), but it does solve the generic stuff. So if you would define classes the following way it will work. Seems good enough to me to close this issue as well, agreed?

```java
abstract class FooResolver<T> {
    String getValue(T foo) {
        return "value"
    }
}

class BarResolver extends FooResolver<Bar> implements GraphQLResolver<Bar> {

}
```

**Comment by oliemansm** [comment] 2018-09-23 06:37
Nevermind. Just created a test with the definition like below, and that one works fine now as well:
```java
abstract class FooResolver<T> implements GraphQLResolver<Bar> {
    String getValue(T foo) {
        return "value"
    }
}

class BarResolver extends FooResolver<Bar> {

}
```

**Closed by oliemansm** 2018-09-23 06:37 UTC

**Comment by mxmlnglt** [comment] 2020-01-02 09:54
> Nevermind. Just created a test with the definition like below, and that one works fine now as well:
> 
> ```java
> abstract class FooResolver<T> implements GraphQLResolver<Bar> {
>     String getValue(T foo) {
>         return "value"
>     }
> }
> 
> class BarResolver extends FooResolver<Bar> {
> 
> }
> ```

@oliemansm: are you sure you didn't actually mean `abstract class FooResolver<T> implements GraphQLResolver<T>`?
