### ISSUE TITLE
MethodFieldResolver should throw a ValidationError type exception

### ISSUE THREAD

**Issue by jdorleans** [graphql-java/graphql-java-tools#71] opened 2017-09-25 20:47 UTC
Currently, when trying to provide graphql `variables` that does not contain the required `data` key/value, graphql-java-tools will run over `MethodFieldResolver` and ultimately throw an `ExceptionWhileDataFetching` type from graphql-java lib. However, from an user perspective, that should rather be a `ValidationError` type to be consistent with any other misrepresented graphql query or data (sort of BadRequest like).

When working and treating exceptions, it's important to have some kind of consistency in between the libs. I'm trying to provide the best feedback possible to my client-side app whenever an error occurs on the server and this behaviour makes things a bit harder since it mix graphql ValidationError and my serve-side internal exception on ExceptionWhileDataFetching.

**Comment by apottere** [comment] 2017-10-09 17:34
Do you have an example of an query and schema that would throw `ExceptionWhileDataFetching` when arguments are passed incorrectly?  I assumed that graphql-java would validate that the arguments are correct before passing them to the `MethodFieldResolver`

**Comment by apottere** [comment] 2017-11-23 19:32
Closing because I can't reproduce - feel free to add some more info and I'll re-open this.

**Closed by apottere** 2017-11-23 19:32 UTC
