### ISSUE TITLE
Object generator based on graphqls

### ISSUE THREAD

**Issue by Salrandin** [graphql-java/graphql-java-tools#109] opened 2018-01-12 00:04 UTC
For my use case I have created an extremely large schema and I do not plan to create resolvers for all of them at the moment.  In order for it to work however the defined schema seems to need resolvers, is it possible or is there:

- A tool to generate all the required objects for the schema based on the graphqls file
- A way to not have to pass explicit resolvers to attributes in the schema and still have the api work?

Thanks.

**Comment by apottere** [comment] 2018-01-12 18:47
I think this is a duplicate of #39

**Closed by apottere** 2018-01-12 18:47 UTC
